# Generated by Django 5.2.16 on 2026-07-28 01:21

import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Capability",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "slug",
                    models.CharField(max_length=64, unique=True, verbose_name="slug"),
                ),
                (
                    "label",
                    models.CharField(max_length=128, unique=True, verbose_name="label"),
                ),
            ],
            options={
                "verbose_name": "capability",
                "verbose_name_plural": "capabilities",
                "ordering": ["slug"],
            },
        ),
        migrations.CreateModel(
            name="RoleGrant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("platform_admin", "platform admin"),
                            ("owner", "firm owner"),
                            ("staff_accountant", "staff accountant"),
                            ("operations_admin", "firm operations admin"),
                            ("client_owner", "MEI client owner"),
                            ("client_collaborator", "MEI client collaborator"),
                        ],
                        max_length=32,
                        verbose_name="role",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("full", "full"),
                            ("none", "none"),
                            ("limited", "limited"),
                            ("view_confirm", "view / confirm"),
                            ("initiate_approve", "initiate / approve"),
                            ("own", "own actions only"),
                            ("ticket_only", "ticket only"),
                        ],
                        max_length=24,
                        verbose_name="level",
                    ),
                ),
                (
                    "capability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grants",
                        to="authz.capability",
                        verbose_name="capability",
                    ),
                ),
            ],
            options={
                "verbose_name": "role grant",
                "verbose_name_plural": "role grants",
                "ordering": ["role"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("role", "capability"),
                        name="rolegrant_role_capability_uniq",
                    )
                ],
            },
        ),
    ]
