# Generated by Django 5.2.16 on 2026-07-29 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from apps.core.migrations._composite_fk import add_tenant_composite_fk


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0010_portal_deny_tag"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="membership",
            name="membership_user_tenant_uniq",
        ),
        migrations.AddField(
            model_name="membership",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="portal_memberships",
                to="clients.clientcompany",
                verbose_name="client",
            ),
        ),
        migrations.AlterField(
            model_name="invite",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "owner"),
                    ("staff_accountant", "staff accountant"),
                    ("operations_admin", "operations admin"),
                    ("client_owner", "MEI client owner"),
                    ("client_collaborator", "MEI client collaborator"),
                ],
                max_length=32,
                verbose_name="role",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "owner"),
                    ("staff_accountant", "staff accountant"),
                    ("operations_admin", "operations admin"),
                    ("client_owner", "MEI client owner"),
                    ("client_collaborator", "MEI client collaborator"),
                ],
                max_length=32,
                verbose_name="role",
            ),
        ),
        migrations.AddConstraint(
            model_name="invite",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "role__in",
                        frozenset(["operations_admin", "owner", "staff_accountant"]),
                    )
                ),
                name="invite_role_is_firm_side",
            ),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(
                fields=("user", "tenant", "client"),
                name="membership_user_tenant_client_uniq",
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("client__isnull", True),
                        (
                            "role__in",
                            frozenset(
                                ["operations_admin", "owner", "staff_accountant"]
                            ),
                        ),
                    ),
                    models.Q(
                        ("client__isnull", False),
                        (
                            "role__in",
                            frozenset(["client_collaborator", "client_owner"]),
                        ),
                    ),
                    _connector="OR",
                ),
                name="membership_role_matches_client_scope",
            ),
        ),
        # Django's own FK checks only client_id. PostgreSQL evaluates referential
        # integrity with row-level security BYPASSED, so nothing above stops a
        # membership pointing at a ClientCompany belonging to a different firm.
        # Pairing tenant_id into the key makes that row unrepresentable.
        # MATCH SIMPLE is the default, so the NULL client_id on every firm-side
        # membership satisfies the constraint without being checked.
        add_tenant_composite_fk(
            table="tenants_membership",
            column="client_id",
            parent_table="clients_clientcompany",
            constraint="membership_tenant_client_fk",
        ),
    ]
