# Generated by Django 5.2.16 on 2026-07-29 18:54

from django.db import migrations, models

import apps.tenants.validators


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0002_portal_client_membership"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="slug",
            field=models.SlugField(
                max_length=63,
                unique=True,
                validators=[apps.tenants.validators.validate_tenant_slug],
                verbose_name="slug",
            ),
        ),
    ]
