# Generated by Django 5.2.16 on 2026-07-30 16:52

from django.db import migrations, models

import apps.core.identifiers


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0003_tenant_slug_reserves_portal_hosts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invite",
            name="id",
            field=models.UUIDField(
                default=apps.core.identifiers.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="id",
            field=models.UUIDField(
                default=apps.core.identifiers.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="id",
            field=models.UUIDField(
                default=apps.core.identifiers.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
