# Generated by Django 5.2.16 on 2026-07-28 04:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ObligationType",
            fields=[
                (
                    "code",
                    models.CharField(
                        max_length=16,
                        primary_key=True,
                        serialize=False,
                        verbose_name="code",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="name")),
                (
                    "periodicity",
                    models.CharField(
                        choices=[("monthly", "monthly"), ("annual", "annual")],
                        max_length=16,
                        verbose_name="periodicity",
                    ),
                ),
                ("due_rule", models.JSONField(verbose_name="due rule")),
                (
                    "source_note",
                    models.TextField(blank=True, verbose_name="source note"),
                ),
                (
                    "source_url",
                    models.URLField(max_length=500, verbose_name="source URL"),
                ),
            ],
            options={
                "verbose_name": "obligation type",
                "verbose_name_plural": "obligation types",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="FiscalParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=64, verbose_name="key")),
                (
                    "mei_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("common", "MEI comum"),
                            ("caminhoneiro", "MEI caminhoneiro"),
                        ],
                        max_length=16,
                        null=True,
                        verbose_name="MEI category",
                    ),
                ),
                ("value", models.CharField(max_length=64, verbose_name="value")),
                ("valid_from", models.DateField(verbose_name="valid from")),
                (
                    "valid_to",
                    models.DateField(blank=True, null=True, verbose_name="valid to"),
                ),
                (
                    "source_note",
                    models.TextField(blank=True, verbose_name="source note"),
                ),
                (
                    "source_url",
                    models.URLField(max_length=500, verbose_name="source URL"),
                ),
            ],
            options={
                "verbose_name": "fiscal parameter",
                "verbose_name_plural": "fiscal parameters",
                "ordering": ["key", "mei_category", "-valid_from"],
                "indexes": [
                    models.Index(
                        fields=["key", "-valid_from"],
                        name="fiscalparameter_key_from_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("key", "mei_category", "valid_from"),
                        name="fiscalparameter_key_category_from_uniq",
                        nulls_distinct=False,
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("valid_to__isnull", True),
                            ("valid_to__gt", models.F("valid_from")),
                            _connector="OR",
                        ),
                        name="fiscalparameter_validity_ordered",
                    ),
                ],
            },
        ),
    ]
