# Generated by Django 5.2.16 on 2026-07-28 05:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("obligations", "0003_seed_obligation_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="date")),
                ("name", models.CharField(max_length=120, verbose_name="name")),
                (
                    "scope",
                    models.CharField(
                        choices=[("national", "national"), ("municipal", "municipal")],
                        default="national",
                        max_length=16,
                        verbose_name="scope",
                    ),
                ),
            ],
            options={
                "verbose_name": "holiday",
                "verbose_name_plural": "holidays",
                "ordering": ["date", "name"],
                "indexes": [
                    models.Index(
                        fields=["scope", "date"], name="holiday_scope_date_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("date", "scope", "name"),
                        name="holiday_date_scope_name_uniq",
                    )
                ],
            },
        ),
    ]
