# Generated by Django 5.2.16 on 2026-07-28 05:13

import django.db.models.deletion
import django.db.models.manager
import uuid6
from django.db import migrations, models

from apps.core.migrations._composite_fk import add_tenant_composite_fk
from apps.core.migrations._operations import EnableRLS


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0007_clientcompany_mei_category"),
        ("obligations", "0005_seed_national_holidays"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchedulerHeartbeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=64, unique=True, verbose_name="name"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "scheduler heartbeat",
                "verbose_name_plural": "scheduler heartbeats",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Obligation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("competence_month", models.DateField(verbose_name="competence month")),
                ("nominal_due_date", models.DateField(verbose_name="nominal due date")),
                (
                    "resolved_due_date",
                    models.DateField(verbose_name="resolved due date"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "scheduled"),
                            ("due", "due"),
                            ("paid", "paid"),
                            ("overdue", "overdue"),
                            ("waived", "waived"),
                        ],
                        default="scheduled",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                (
                    "evidence_ref",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="evidence reference"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="obligations",
                        to="clients.clientcompany",
                        verbose_name="client",
                    ),
                ),
                (
                    "obligation_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="obligations",
                        to="obligations.obligationtype",
                        verbose_name="obligation type",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tenants.tenant",
                        verbose_name="tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "obligation",
                "verbose_name_plural": "obligations",
                "ordering": ["competence_month"],
                "abstract": False,
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["tenant", "resolved_due_date"],
                        name="obligation_tenant_due_idx",
                    ),
                    models.Index(
                        fields=["tenant", "status"], name="obligation_tenant_status_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "tenant",
                            "client",
                            "obligation_type",
                            "competence_month",
                        ),
                        name="obligation_tenant_client_type_competence_uniq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("competence_month__day", 1)),
                        name="obligation_competence_is_month_start",
                    ),
                ],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
        EnableRLS("Obligation"),
        # Row-level security does NOT police foreign-key checks -- PostgreSQL
        # documents that referential integrity bypasses row security -- so a plain
        # client_id proves only that the client exists somewhere. Pairing the tenant
        # into the key makes a cross-tenant reference structurally impossible.
        add_tenant_composite_fk(
            table="obligations_obligation",
            column="client_id",
            parent_table="clients_clientcompany",
            constraint="obligation_tenant_client_fk",
        ),
    ]
