# Generated by Django 5.2.16 on 2026-07-28 05:24

import django.db.models.deletion
import django.db.models.manager
import uuid6
from django.db import migrations, models

from apps.core.migrations._composite_fk import add_tenant_composite_fk
from apps.core.migrations._operations import EnableRLS


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0007_clientcompany_mei_category"),
        ("obligations", "0007_arm_scheduler_heartbeat"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlyRevenue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("competence_month", models.DateField(verbose_name="competence month")),
                (
                    "gross_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="gross amount"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_revenues",
                        to="clients.clientcompany",
                        verbose_name="client",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tenants.tenant",
                        verbose_name="tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "monthly revenue",
                "verbose_name_plural": "monthly revenues",
                "ordering": ["competence_month"],
                "abstract": False,
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["tenant", "competence_month"],
                        name="revenue_tenant_competence_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "client", "competence_month"),
                        name="monthlyrevenue_tenant_client_competence_uniq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("competence_month__day", 1)),
                        name="monthlyrevenue_competence_is_month_start",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("gross_amount__gte", 0)),
                        name="monthlyrevenue_gross_amount_not_negative",
                    ),
                ],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
        EnableRLS("MonthlyRevenue"),
        # Referential-integrity checks bypass row security, so a plain client_id
        # proves only that the client exists somewhere. Pairing the tenant into the
        # key makes a cross-tenant revenue entry structurally impossible.
        add_tenant_composite_fk(
            table="obligations_monthlyrevenue",
            column="client_id",
            parent_table="clients_clientcompany",
            constraint="monthlyrevenue_tenant_client_fk",
        ),
    ]
