# Generated by Django 5.2.16 on 2026-07-30 16:52

from django.db import migrations, models

import apps.core.identifiers


class Migration(migrations.Migration):
    dependencies = [
        ("obligations", "0009_portal_client_policies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monthlyrevenue",
            name="id",
            field=models.UUIDField(
                default=apps.core.identifiers.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="obligation",
            name="id",
            field=models.UUIDField(
                default=apps.core.identifiers.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
