# Generated by Django 5.2.16 on 2026-07-31 01:47

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models

import apps.core.identifiers
import apps.obligations.models.documents
from apps.core.migrations._operations import EnableRLS


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0011_alter_clientassignment_id_alter_clientcompany_id_and_more"),
        ("obligations", "0010_alter_monthlyrevenue_id_alter_obligation_id"),
        ("tenants", "0004_alter_invite_id_alter_membership_id_alter_tenant_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=apps.core.identifiers.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "storage_key",
                    models.CharField(
                        default=apps.obligations.models.documents.new_storage_key,
                        editable=False,
                        max_length=128,
                        verbose_name="storage key",
                    ),
                ),
                ("sha256", models.CharField(max_length=64, verbose_name="sha256")),
                (
                    "original_filename",
                    models.CharField(max_length=255, verbose_name="original filename"),
                ),
                (
                    "content_type",
                    models.CharField(max_length=127, verbose_name="content type"),
                ),
                ("byte_size", models.PositiveBigIntegerField(verbose_name="byte size")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="clients.clientcompany",
                        verbose_name="client",
                    ),
                ),
                (
                    "obligation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="obligations.obligation",
                        verbose_name="obligation",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tenants.tenant",
                        verbose_name="tenant",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="uploaded by",
                    ),
                ),
            ],
            options={
                "verbose_name": "document",
                "verbose_name_plural": "documents",
                "ordering": ["-created_at"],
                "abstract": False,
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["tenant", "client", "created_at"],
                        name="doc_tenant_client_created_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "client", "storage_key"),
                        name="document_tenant_client_storage_key_uniq",
                    ),
                    models.UniqueConstraint(
                        fields=("tenant", "client", "sha256"),
                        name="document_tenant_client_sha256_uniq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("byte_size__gt", 0)),
                        name="document_byte_size_positive",
                    ),
                ],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
        EnableRLS("Document"),
    ]
