# Generated by Django 5.2.16 on 2026-07-31 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("obligations", "0013_document_client_paired_fk"),
    ]

    operations = [
        migrations.CreateModel(
            name="ObligationDueRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rule", models.JSONField(verbose_name="rule")),
                ("valid_from", models.DateField(verbose_name="valid from")),
                (
                    "valid_to",
                    models.DateField(blank=True, null=True, verbose_name="valid to"),
                ),
                (
                    "source_note",
                    models.TextField(blank=True, verbose_name="source note"),
                ),
                (
                    "source_url",
                    models.URLField(max_length=500, verbose_name="source URL"),
                ),
                (
                    "obligation_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="due_rules",
                        to="obligations.obligationtype",
                        verbose_name="obligation type",
                    ),
                ),
            ],
            options={
                "verbose_name": "obligation due rule",
                "verbose_name_plural": "obligation due rules",
                "ordering": ["obligation_type", "-valid_from"],
                "indexes": [
                    models.Index(
                        fields=["obligation_type", "-valid_from"],
                        name="duerule_type_from_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("obligation_type", "valid_from"),
                        name="obligationduerule_type_from_uniq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("valid_to__isnull", True),
                            ("valid_to__gt", models.F("valid_from")),
                            _connector="OR",
                        ),
                        name="obligationduerule_validity_ordered",
                    ),
                ],
            },
        ),
    ]
