# Generated by Django 5.2.16 on 2026-08-01 01:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("obligations", "0016_remove_obligationtype_due_rule"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedulerheartbeat",
            name="free_disk_kib",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="free disk KiB"
            ),
        ),
    ]
