# Generated by Django 5.2.16 on 2026-07-28 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Municipality",
            fields=[
                (
                    "ibge_code",
                    models.CharField(
                        max_length=7,
                        primary_key=True,
                        serialize=False,
                        verbose_name="IBGE code",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="name")),
                (
                    "uf",
                    models.CharField(
                        choices=[
                            ("AC", "Acre"),
                            ("AL", "Alagoas"),
                            ("AP", "Amapá"),
                            ("AM", "Amazonas"),
                            ("BA", "Bahia"),
                            ("CE", "Ceará"),
                            ("DF", "Distrito Federal"),
                            ("ES", "Espírito Santo"),
                            ("GO", "Goiás"),
                            ("MA", "Maranhão"),
                            ("MT", "Mato Grosso"),
                            ("MS", "Mato Grosso do Sul"),
                            ("MG", "Minas Gerais"),
                            ("PA", "Pará"),
                            ("PB", "Paraíba"),
                            ("PR", "Paraná"),
                            ("PE", "Pernambuco"),
                            ("PI", "Piauí"),
                            ("RJ", "Rio de Janeiro"),
                            ("RN", "Rio Grande do Norte"),
                            ("RS", "Rio Grande do Sul"),
                            ("RO", "Rondônia"),
                            ("RR", "Roraima"),
                            ("SC", "Santa Catarina"),
                            ("SP", "São Paulo"),
                            ("SE", "Sergipe"),
                            ("TO", "Tocantins"),
                        ],
                        max_length=2,
                        verbose_name="UF",
                    ),
                ),
            ],
            options={
                "verbose_name": "municipality",
                "verbose_name_plural": "municipalities",
                "ordering": ["uf", "name"],
                "indexes": [models.Index(fields=["uf"], name="municipality_uf_idx")],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("ibge_code__regex", "^[0-9]{7}$")),
                        name="municipality_ibge_code_is_seven_digits",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MunicipalityCapability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nfse_national_emitter",
                    models.BooleanField(
                        default=False, verbose_name="uses the national NFS-e emitter"
                    ),
                ),
                (
                    "requires_certificate",
                    models.BooleanField(
                        default=True, verbose_name="requires a digital certificate"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "verified_on",
                    models.DateField(blank=True, null=True, verbose_name="verified on"),
                ),
                (
                    "municipality",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capability",
                        to="fiscal.municipality",
                        verbose_name="municipality",
                    ),
                ),
            ],
            options={
                "verbose_name": "municipality capability",
                "verbose_name_plural": "municipality capabilities",
                "ordering": ["municipality"],
            },
        ),
    ]
