# Generated by Django 5.2.16 on 2026-07-27 22:42

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core_tests", "0002_enable_rls"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="exampletenantmodel",
            managers=[
                ("scoped", django.db.models.manager.Manager()),
            ],
        ),
    ]
