# Generated by Django 5.2.16 on 2026-07-27 22:46

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core_tests", "0003_alter_exampletenantmodel_managers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exampletenantmodel",
            options={
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
        ),
        migrations.AlterModelManagers(
            name="exampletenantmodel",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
