# Generated by Django 5.2.16 on 2026-07-31 13:33

from django.db import migrations, models

import apps.core.identifiers


class Migration(migrations.Migration):
    dependencies = [
        ("core_tests", "0004_alter_exampletenantmodel_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exampletenantmodel",
            name="id",
            field=models.UUIDField(
                default=apps.core.identifiers.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
