"""The tenancy root must be unguessable, unique per user, and never store a raw token.

`Tenant`, `Membership` and `Invite` are deliberately NOT row-level-security scoped: the
middleware reads `Membership` to discover which tenant a request belongs to, which
happens before `app.tenant_id` can exist. Policing them with an `app.tenant_id` policy
would make that lookup return zero rows and no user could ever sign in.
"""

import uuid

import pytest
from django.db import IntegrityError, connection, transaction

from apps.accounts.models import User
from apps.tenants.models import Invite, Membership, Tenant, TenantRole

pytestmark = pytest.mark.django_db


def _tenant(slug: str = "acme") -> Tenant:
    return Tenant.objects.create(name=slug.title(), slug=slug)


def test_tenant_primary_key_is_a_version_7_uuid() -> None:
    # Given a newly created tenant
    tenant = _tenant()

    # When its primary key is inspected
    # Then it is a time-ordered UUIDv7, not a random UUIDv4
    assert isinstance(tenant.id, uuid.UUID)
    assert tenant.id.version == 7


def test_membership_is_unique_per_user_and_tenant() -> None:
    # Given a user who already belongs to a tenant
    user = User.objects.create_user(email="owner@example.com")
    tenant = _tenant()
    Membership.objects.create(user=user, tenant=tenant, role=TenantRole.OWNER)

    # When the same pair is inserted again
    # Then the database refuses it rather than silently duplicating the grant
    with pytest.raises(IntegrityError), transaction.atomic():
        Membership.objects.create(
            user=user,
            tenant=tenant,
            role=TenantRole.STAFF_ACCOUNTANT,
        )


def test_membership_is_readable_with_no_tenant_context() -> None:
    # Given a membership and an explicitly empty tenant GUC, as on a fresh connection
    user = User.objects.create_user(email="login@example.com")
    tenant = _tenant()
    Membership.objects.create(user=user, tenant=tenant, role=TenantRole.OWNER)
    with connection.cursor() as cursor:
        cursor.execute("SELECT set_config('app.tenant_id', '', true)")

        # When the login path resolves the user's memberships
        found = list(Membership.objects.filter(user=user))

    # Then the lookup succeeds — this is the bootstrap read the middleware depends on
    assert [m.tenant_id for m in found] == [tenant.id]


def test_invite_never_stores_the_raw_token() -> None:
    # Given an invite issued with a freshly generated token
    tenant = _tenant()
    invite, raw_token = Invite.issue(
        tenant=tenant,
        email="invitee@example.com",
        role=TenantRole.STAFF_ACCOUNTANT,
    )

    # When every stored column is dumped
    stored = str(list(Invite.objects.values_list()))

    # Then the raw token appears nowhere, only its digest
    assert raw_token not in stored
    assert invite.token != raw_token
    assert invite.token in stored


def test_invite_token_carries_at_least_32_bytes_of_entropy() -> None:
    # Given a token generated by the issuing helper
    _, raw_token = Invite.issue(
        tenant=_tenant(),
        email="entropy@example.com",
        role=TenantRole.OWNER,
    )

    # When its length is measured
    # Then it is at least the 43 characters that 32 urlsafe-base64 bytes produce
    assert len(raw_token) >= 43


def test_invite_is_found_by_hashing_the_presented_token() -> None:
    # Given an issued invite
    tenant = _tenant()
    invite, raw_token = Invite.issue(
        tenant=tenant,
        email="lookup@example.com",
        role=TenantRole.OWNER,
    )

    # When the raw token is presented for redemption
    # Then it resolves to the stored digest, and a wrong token resolves to nothing
    assert Invite.objects.get(token=Invite.hash_token(raw_token)).pk == invite.pk
    assert not Invite.objects.filter(token=Invite.hash_token("wrong")).exists()


def test_tenancy_root_tables_carry_no_row_level_security_policy() -> None:
    # Given the tenancy root tables, which the middleware must read before any context
    roots = ["tenants_tenant", "tenants_membership", "tenants_invite"]

    # When pg_policies is queried for them
    with connection.cursor() as cursor:
        cursor.execute(
            "SELECT tablename FROM pg_policies WHERE tablename = ANY(%s)",
            [roots],
        )
        policed = [row[0] for row in cursor.fetchall()]

    # Then none of them is policed — policing them would break the login path
    assert policed == []
