# Generated by Django 5.2.16 on 2026-07-28 00:13

import django.db.models.deletion
import django.db.models.manager
import uuid6
from django.conf import settings
from django.db import migrations, models

from apps.audit.appendonly import make_append_only
from apps.core.migrations._operations import EnableRLS


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login_succeeded", "login succeeded"),
                            ("login_failed", "login failed"),
                            ("logout", "logout"),
                            ("mfa_enrolled", "MFA enrolled"),
                            ("mfa_removed", "MFA removed"),
                            ("mfa_reset", "MFA reset"),
                            ("password_changed", "password changed"),
                            ("invite_issued", "invite issued"),
                            ("invite_accepted", "invite accepted"),
                            ("role_changed", "role changed"),
                            ("assignment_changed", "assignment changed"),
                            ("connector_connected", "connector connected"),
                            ("connector_disconnected", "connector disconnected"),
                            ("invoice_attempted", "invoice attempted"),
                            ("das_confirmed", "DAS confirmed"),
                            ("declaration_submitted", "declaration submitted"),
                            ("export", "export"),
                            ("impersonation", "impersonation"),
                            ("tenant_selected", "tenant selected"),
                            ("all_tenants_access", "cross-tenant access"),
                            ("dsr_submitted", "data subject request submitted"),
                            ("denied", "action denied"),
                        ],
                        max_length=48,
                        verbose_name="action",
                    ),
                ),
                (
                    "object_type",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="object type"
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="object id"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="metadata"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="actor",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tenants.tenant",
                        verbose_name="tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "audit event",
                "verbose_name_plural": "audit events",
                "ordering": ["-created_at"],
                "abstract": False,
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["tenant", "-created_at"], name="audit_event_tenant_ts"
                    ),
                    models.Index(
                        fields=["tenant", "action"], name="audit_event_tenant_action"
                    ),
                ],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="PlatformEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login_succeeded", "login succeeded"),
                            ("login_failed", "login failed"),
                            ("logout", "logout"),
                            ("mfa_enrolled", "MFA enrolled"),
                            ("mfa_removed", "MFA removed"),
                            ("mfa_reset", "MFA reset"),
                            ("password_changed", "password changed"),
                            ("invite_issued", "invite issued"),
                            ("invite_accepted", "invite accepted"),
                            ("role_changed", "role changed"),
                            ("assignment_changed", "assignment changed"),
                            ("connector_connected", "connector connected"),
                            ("connector_disconnected", "connector disconnected"),
                            ("invoice_attempted", "invoice attempted"),
                            ("das_confirmed", "DAS confirmed"),
                            ("declaration_submitted", "declaration submitted"),
                            ("export", "export"),
                            ("impersonation", "impersonation"),
                            ("tenant_selected", "tenant selected"),
                            ("all_tenants_access", "cross-tenant access"),
                            ("dsr_submitted", "data subject request submitted"),
                            ("denied", "action denied"),
                        ],
                        max_length=48,
                        verbose_name="action",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True, max_length=254, verbose_name="subject"
                    ),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP address"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="metadata"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="platform_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="actor",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="platform_events",
                        to="tenants.tenant",
                        verbose_name="tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "platform event",
                "verbose_name_plural": "platform events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["-created_at"], name="audit_platform_ts"),
                    models.Index(
                        fields=["action", "-created_at"], name="audit_platform_action"
                    ),
                ],
            },
        ),
        # Event is tenant-scoped like every business table. PlatformEvent deliberately
        # is NOT: its WITH CHECK half would reject a login-failure row, which by
        # definition has no resolved tenant behind it. It is allow-listed in
        # apps.core.rls.NON_TENANT_TABLES in the same commit.
        EnableRLS("Event"),
        # Grants alone would leave app_migrator and app_test — which own these tables
        # and hold BYPASSRLS — free to rewrite the trail. The trigger binds them too.
        *make_append_only("audit_event", "audit_platformevent"),
    ]
