# Generated by Django 5.2.16 on 2026-07-28 00:39

import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0002_accesslog"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSubjectRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "requester_name",
                    models.CharField(max_length=255, verbose_name="requester name"),
                ),
                ("cpf", models.CharField(max_length=14, verbose_name="CPF")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="email address"),
                ),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("holder", "holder"),
                            ("representative", "representative"),
                        ],
                        max_length=20,
                        verbose_name="relationship",
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("access", "access"),
                            ("correction", "correction"),
                            ("deletion", "deletion"),
                            ("portability", "portability"),
                            ("restriction", "restriction"),
                        ],
                        max_length=20,
                        verbose_name="request type",
                    ),
                ),
                ("detail", models.TextField(blank=True, verbose_name="detail")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="resolved at"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="data_subject_requests",
                        to="tenants.tenant",
                        verbose_name="tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "data subject request",
                "verbose_name_plural": "data subject requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
