# Generated by Django 5.2.16 on 2026-07-30 16:52

from django.db import migrations, models

import apps.core.identifiers


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0004_portal_deny_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesslog",
            name="id",
            field=models.UUIDField(
                default=apps.core.identifiers.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="datasubjectrequest",
            name="id",
            field=models.UUIDField(
                default=apps.core.identifiers.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="id",
            field=models.UUIDField(
                default=apps.core.identifiers.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="platformevent",
            name="id",
            field=models.UUIDField(
                default=apps.core.identifiers.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
