# Generated by Django 5.2.16 on 2026-08-10 23:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0006_alter_event_action_alter_platformevent_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasubjectrequest",
            name="encarregado_notified_at",
            field=models.DateTimeField(
                null=True, verbose_name="encarregado notified at"
            ),
        ),
        migrations.AddField(
            model_name="datasubjectrequest",
            name="notification_last_error",
            field=models.TextField(blank=True, verbose_name="notification last error"),
        ),
    ]
