# Generated by Django 5.2.16 on 2026-07-28 01:04

import django.db.models.deletion
import django.db.models.manager
import uuid6
from django.db import migrations, models

from apps.core.migrations._operations import EnableRLS


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientCompany",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "legal_name",
                    models.CharField(max_length=255, verbose_name="legal name"),
                ),
                (
                    "trade_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="trade name"
                    ),
                ),
                ("cnpj", models.CharField(max_length=14, verbose_name="CNPJ")),
                (
                    "cpf",
                    models.CharField(
                        blank=True, max_length=11, null=True, verbose_name="CPF"
                    ),
                ),
                (
                    "municipality_ibge_code",
                    models.CharField(
                        blank=True, max_length=7, verbose_name="IBGE municipality code"
                    ),
                ),
                (
                    "state",
                    models.CharField(blank=True, max_length=2, verbose_name="state"),
                ),
                (
                    "main_cnae",
                    models.CharField(
                        blank=True, max_length=7, verbose_name="main CNAE"
                    ),
                ),
                (
                    "opened_on",
                    models.DateField(blank=True, null=True, verbose_name="opened on"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("onboarding", "onboarding"),
                            ("active", "active"),
                            ("suspended", "suspended"),
                            ("closed", "closed"),
                        ],
                        default="onboarding",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("is_mei", models.BooleanField(default=True, verbose_name="MEI")),
                (
                    "has_employee",
                    models.BooleanField(default=False, verbose_name="has employee"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tenants.tenant",
                        verbose_name="tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "client company",
                "verbose_name_plural": "client companies",
                "ordering": ["legal_name"],
                "abstract": False,
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["tenant", "status"], name="client_tenant_status_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "cnpj"), name="clientcompany_tenant_cnpj_uniq"
                    ),
                    models.UniqueConstraint(
                        fields=("tenant", "id"), name="clientcompany_tenant_id_uniq"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("cnpj__regex", "^[0-9A-Z]{14}$")),
                        name="clientcompany_cnpj_normalized",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("cpf__isnull", True),
                            ("cpf__regex", "^[0-9A-Z]{11}$"),
                            _connector="OR",
                        ),
                        name="clientcompany_cpf_normalized",
                    ),
                ],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
        EnableRLS("ClientCompany"),
    ]
