# Generated by Django 5.2.16 on 2026-07-28 01:12

import django.db.models.deletion
import django.db.models.manager
import uuid6
from django.conf import settings
from django.db import migrations, models

from apps.core.migrations._composite_fk import add_tenant_composite_fk
from apps.core.migrations._operations import EnableRLS


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0001_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="clientcompany",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="ClientTag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tag_links",
                        to="clients.clientcompany",
                        verbose_name="client",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tenants.tenant",
                        verbose_name="tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "client tag",
                "verbose_name_plural": "client tags",
                "abstract": False,
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="name")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "clients",
                    models.ManyToManyField(
                        related_name="tags",
                        through="clients.ClientTag",
                        to="clients.clientcompany",
                        verbose_name="clients",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tenants.tenant",
                        verbose_name="tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "tag",
                "verbose_name_plural": "tags",
                "ordering": ["name"],
                "abstract": False,
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="clienttag",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_links",
                to="clients.tag",
                verbose_name="tag",
            ),
        ),
        migrations.CreateModel(
            name="ClientAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("primary", "primary"), ("support", "support")],
                        default="primary",
                        max_length=16,
                        verbose_name="role",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="clients.clientcompany",
                        verbose_name="client",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tenants.tenant",
                        verbose_name="tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "client assignment",
                "verbose_name_plural": "client assignments",
                "abstract": False,
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["tenant", "user"], name="assignment_tenant_user_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "client", "user"),
                        name="clientassignment_tenant_client_user_uniq",
                    )
                ],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(
                fields=("tenant", "name"), name="tag_tenant_name_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(
                fields=("tenant", "id"), name="tag_tenant_id_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="clienttag",
            index=models.Index(
                fields=["tenant", "tag"], name="clienttag_tenant_tag_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="clienttag",
            constraint=models.UniqueConstraint(
                fields=("tenant", "client", "tag"),
                name="clienttag_tenant_client_tag_uniq",
            ),
        ),
        EnableRLS("ClientAssignment"),
        EnableRLS("Tag"),
        EnableRLS("ClientTag"),
        # Row-level security does NOT police foreign-key checks, so each of these
        # pairs the tenant into the key. Ordered after the AddConstraint operations
        # above because tag_tenant_id_uniq is the referent of the last one.
        add_tenant_composite_fk(
            table="clients_clientassignment",
            column="client_id",
            parent_table="clients_clientcompany",
            constraint="clientassignment_tenant_client_fk",
        ),
        add_tenant_composite_fk(
            table="clients_clienttag",
            column="client_id",
            parent_table="clients_clientcompany",
            constraint="clienttag_tenant_client_fk",
        ),
        add_tenant_composite_fk(
            table="clients_clienttag",
            column="tag_id",
            parent_table="clients_tag",
            constraint="clienttag_tenant_tag_fk",
        ),
    ]
