# Generated by Django 5.2.16 on 2026-07-28 01:42

import django.db.models.deletion
import django.db.models.manager
import uuid6
from django.db import migrations, models

from apps.core.migrations._composite_fk import add_tenant_composite_fk
from apps.core.migrations._operations import EnableRLS


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0002_assignments_and_tags"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OnboardingItemTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "key",
                    models.CharField(max_length=64, unique=True, verbose_name="key"),
                ),
                ("label", models.CharField(max_length=255, verbose_name="label")),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="position"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
            ],
            options={
                "verbose_name": "onboarding item template",
                "verbose_name_plural": "onboarding item templates",
                "ordering": ["position", "key"],
            },
        ),
        migrations.CreateModel(
            name="OnboardingItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(max_length=64, verbose_name="key")),
                ("label", models.CharField(max_length=255, verbose_name="label")),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="position"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("blocked", "blocked"),
                            ("done", "done"),
                            ("not_applicable", "not applicable"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "blocked_reason",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="blocked reason"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="completed at"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_items",
                        to="clients.clientcompany",
                        verbose_name="client",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tenants.tenant",
                        verbose_name="tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "onboarding item",
                "verbose_name_plural": "onboarding items",
                "ordering": ["position", "key"],
                "abstract": False,
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
                "indexes": [
                    models.Index(
                        fields=["tenant", "status"], name="onboarding_tenant_status_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "client", "key"),
                        name="onboardingitem_tenant_client_key_uniq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "blocked"), _negated=True),
                            models.Q(("blocked_reason", ""), _negated=True),
                            _connector="OR",
                        ),
                        name="onboardingitem_blocked_needs_a_reason",
                    ),
                ],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
                ("objects", django.db.models.manager.Manager()),
            ],
        ),
        EnableRLS("OnboardingItem"),
        # Row-level security does not police foreign-key checks, so the key pairs the
        # tenant in. OnboardingItemTemplate is platform level and needs neither.
        add_tenant_composite_fk(
            table="clients_onboardingitem",
            column="client_id",
            parent_table="clients_clientcompany",
            constraint="onboardingitem_tenant_client_fk",
        ),
    ]
