# Generated by Django 5.2.16 on 2026-07-28 01:49

from django.apps import registry as app_registry
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor

# Settling these two needs the e-CAC portal, which admits only prata and ouro gov.br
# accounts. Held as data so a change in Receita Federal's portal routing is an UPDATE
# rather than a release.
ECAC_KEYS = ("first_das_schedule", "annual_declaration")


def mark_ecac_items(apps: app_registry.Apps, _editor: BaseDatabaseSchemaEditor) -> None:
    """Flag the seeded template rows that route through e-CAC."""
    template_model = apps.get_model("clients", "OnboardingItemTemplate")
    template_model.objects.filter(key__in=ECAC_KEYS).update(requires_ecac=True)


def unmark_ecac_items(
    apps: app_registry.Apps,
    _editor: BaseDatabaseSchemaEditor,
) -> None:
    """Clear the flag again."""
    template_model = apps.get_model("clients", "OnboardingItemTemplate")
    template_model.objects.filter(key__in=ECAC_KEYS).update(requires_ecac=False)


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0004_seed_checklist_templates"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientcompany",
            name="certificate_expires_on",
            field=models.DateField(
                blank=True, null=True, verbose_name="certificate expires on"
            ),
        ),
        migrations.AddField(
            model_name="clientcompany",
            name="govbr_trust_level",
            field=models.CharField(
                choices=[
                    ("unknown", "unknown"),
                    ("bronze", "bronze"),
                    ("prata", "prata"),
                    ("ouro", "ouro"),
                ],
                default="unknown",
                max_length=16,
                verbose_name="gov.br trust level",
            ),
        ),
        migrations.AddField(
            model_name="clientcompany",
            name="has_digital_certificate",
            field=models.BooleanField(
                default=False, verbose_name="has digital certificate"
            ),
        ),
        migrations.AddField(
            model_name="onboardingitem",
            name="requires_ecac",
            field=models.BooleanField(default=False, verbose_name="requires e-CAC"),
        ),
        migrations.AddField(
            model_name="onboardingitemtemplate",
            name="requires_ecac",
            field=models.BooleanField(default=False, verbose_name="requires e-CAC"),
        ),
        migrations.RunPython(mark_ecac_items, unmark_ecac_items),
    ]
