# Generated by Django 5.2.16 on 2026-07-28 03:40

from django.db import migrations, models

import apps.fiscal.validators


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0005_readiness_and_govbr_trust"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientcompany",
            name="cnpj",
            field=models.CharField(
                max_length=14,
                validators=[apps.fiscal.validators.validate_cnpj],
                verbose_name="CNPJ",
            ),
        ),
        migrations.AlterField(
            model_name="clientcompany",
            name="cpf",
            field=models.CharField(
                blank=True,
                max_length=11,
                null=True,
                validators=[apps.fiscal.validators.validate_cpf],
                verbose_name="CPF",
            ),
        ),
    ]
