# Generated by Django 5.2.16 on 2026-07-28 04:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0006_alter_clientcompany_cnpj_alter_clientcompany_cpf"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientcompany",
            name="mei_category",
            field=models.CharField(
                choices=[("common", "MEI comum"), ("caminhoneiro", "MEI caminhoneiro")],
                default="common",
                max_length=16,
                verbose_name="MEI category",
            ),
        ),
    ]
