# Generated by Django 5.2.16 on 2026-07-30 16:52

from django.db import migrations, models

import apps.core.identifiers


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0010_portal_deny_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientassignment",
            name="id",
            field=models.UUIDField(
                default=apps.core.identifiers.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="clientcompany",
            name="id",
            field=models.UUIDField(
                default=apps.core.identifiers.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="clienttag",
            name="id",
            field=models.UUIDField(
                default=apps.core.identifiers.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="onboardingitem",
            name="id",
            field=models.UUIDField(
                default=apps.core.identifiers.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="onboardingitemtemplate",
            name="id",
            field=models.UUIDField(
                default=apps.core.identifiers.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="id",
            field=models.UUIDField(
                default=apps.core.identifiers.uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
